<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="<?= DOMEN; ?>public/css/reset.css">
    <link rel="stylesheet" href="<?= DOMEN; ?>public/css/style.css">
    <title>Jokes</title>
</head>
<body>
<header>
    <h1>jokes</h1>
</header>