
<?php include_once $_SERVER['DOCUMENT_ROOT'] . '/includes/layouts/header.phtml';?>
<?php include_once $_SERVER['DOCUMENT_ROOT'] . '/includes/layouts/navigation.phtml'; ?>

<section>
    <div class="hello-block">
        <p>
            Привет, Гость! <br>
            Желаешь <a href="<?= DOMEN; ?>public/login/?signin">войти</a><br>
            или <a href="<?= DOMEN; ?>public/login/?signup">зарегистрироваться</a>?
        </p>
    </div>
    <div class="jokes">
        <?php while ($row = $resultJoke->fetch()): ?>
            <div class="joke">
                <span>Категории: <?= categories_for_joke($row['joke_id']) ?></span>
                <p>
                    <?= htmlentities($row['joke_text']); ?><br>
                </p>
                <span class="date-pub">Время публикации: <?= htmlentities($row['joke_date']); ?></span>
            </div>
        <?php endwhile; ?>
    </div>
    <div class="page-nav">
        <?php indexed_links($page, $pages); ?>
    </div>
</section>

<?php include_once $_SERVER['DOCUMENT_ROOT'] . '/includes/layouts/footer.phtml';?>
