
<?php include_once $_SERVER['DOCUMENT_ROOT'] . '/includes/layouts/header.phtml';?>
<?php include_once $_SERVER['DOCUMENT_ROOT'] . '/includes/layouts/navigation.phtml'; ?>

<section>
    <?php if (! empty($_SESSION['id'])) {print hello_block_authorization();}
          else {print hello_block();} ?>
    <?php if (! empty($_SESSION['message'])) {print session_message();} ?>
    <?php if (! empty($_SESSION['errors'])) {print session_errors();} ?>
    <?php if (! empty($_SESSION['type'])) {print addJokeLink();} ?>

    <div class="jokes">
        <?php while ($row = $resultJoke->fetch()): ?>
            <div class="joke">
                <a href="?author=<?= $row['user_id']; ?>" class="author-link-jokes"><?= htmlentities($row['name'])
                                                                                        . ' ' . htmlentities($row['surname']); ?>
                </a><br>
                <span>Категории: <?= categories_for_joke($row['joke_id']) ?></span>
                <p>
                    <?= htmlentities($row['joke_text']); ?><br>
                </p>
                <span class="date-pub">Время публикации: <?= htmlentities($row['joke_date']); ?></span><br>
                <?php if ($_SESSION['id'] === $row['user_id'] || $_SESSION['type'] === 'admin') {
                    print '<a href="' . DOMEN . 'public/admin/jokes/?updatejoke=' . $row['joke_id'] . '" class="button">Редактировать</a>';
                } ?>
            </div>
        <?php endwhile; ?>
    </div>
    <div class="page-nav">
        <?php indexed_links($page, $pages); ?>
    </div>
</section>

<?php include_once $_SERVER['DOCUMENT_ROOT'] . '/includes/layouts/footer.phtml';?>
