
<?php include_once $_SERVER['DOCUMENT_ROOT'] . '/includes/layouts/header.phtml';?>
<?php include_once $_SERVER['DOCUMENT_ROOT'] . '/includes/layouts/navigation.phtml'; ?>

<section>
    <?php if (isset($_SESSION['id']) and strlen($_SESSION['id']) > 0) {print hello_block_authorization();}
          else {print hello_block();} ?>
    <div class="jokes">
        <?php while ($row = $resultJoke->fetch()): ?>
            <div class="joke">
                <a href="?author=<?= $row['user_id']; ?>" class="author-link-jokes"><?= $row['name'] . ' ' . $row['surname']; ?></a><br>
                <span>Категории: <?= categories_for_joke($row['joke_id']) ?></span>
                <p>
                    <?= htmlentities($row['joke_text']); ?><br>
                </p>
                <span class="date-pub">Время публикации: <?= htmlentities($row['joke_date']); ?></span>
            </div>
        <?php endwhile; ?>
    </div>
    <div class="page-nav">
        <?php indexed_links($page, $pages); ?>
    </div>
</section>

<?php include_once $_SERVER['DOCUMENT_ROOT'] . '/includes/layouts/footer.phtml';?>
