
<nav>
    <div class="navigation">
        <?php if ($_SESSION['type'] === 'admin'): ?>
            <a href="<?= DOMEN . 'public/admin/categories/?addcategory'; ?>" class="category new-category">
                + Создать новую категорию</a>
        <?php endif; ?>
        <a href="?category=all"
           class="category major-category<?php if ($category == 'all') {print ' inactive';} ?>">
            Показать всё</a><br>
        <div class="bd-cat">
            <?php while ($row = $resultCategory->fetch()): ?>
                <a href="?category=<?= $row['category_id'] ?>"
                   class="category<?php if ($category == $row['category_id']) {print ' inactive';} ?>">
                    <?= $row['category_name']; ?></a><br>
                <?php if ($category == $row['category_id'] && $_SESSION['type'] === 'admin'): ?>
                    <ul>
                        <li><a href="<?= DOMEN . 'public/admin/categories/?updatecategory=' . $row['category_id']; ?>"
                               class="category">Редактировать категорию</a><br></li>
                        <li><a href="<?= DOMEN . 'public/admin/categories/?deletecategory=' . $row['category_id']; ?>"
                               class="category">Удалить категорию</a><br></li>
                    </ul>
                <?php endif; ?>
            <?php endwhile; ?>
        </div>
    </div>
</nav>