
<?php include_once $_SERVER['DOCUMENT_ROOT'] . '/includes/layouts/header.phtml'; ?>

<section></section>
<section>
    <?php if (! empty($_SESSION['errors'])) {print session_errors();} ?>
    <?php if (! empty($_SESSION['message'])) {print session_message();} ?>
    <form method="post" class="form">
        <span>Вход</span><br>
        <label for="email">Введите эмейл: </label>
        <input type="text" name="email"><br>
        <label for="password">Введите пароль: </label>
        <input type="password" name="password"><br>
        <input type="submit" name="signin" value="Войти">
        <a href="<?= DOMEN . 'public/' ?>" class="button">Отмена</a>
    </form>
</section>

<?php include_once $_SERVER['DOCUMENT_ROOT'] . '/includes/layouts/footer.phtml'; ?>
